---
version: '3.4'
services:
  weaviate-backup:
    image: semitechnologies/weaviate:${WEAVIATE_VERSION}
    restart: on-failure:0
    ports:
      - 8089:8080
      - 50060:50051
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./weaviate-data"
      BACKUP_FILESYSTEM_PATH: "/tmp/backups"
      ENABLE_MODULES: backup-filesystem
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      DISABLE_TELEMETRY: 'true'
...
