---
version: '3.4'
services:
  weaviate-proxy:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8020'
      - --scheme
      - http
      - --write-timeout=600s
    image: semitechnologies/weaviate:${WEAVIATE_VERSION}
    restart: on-failure:0
    environment:
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      ENABLE_MODULES: text2vec-contextionary
      BACKUP_FILESYSTEM_PATH: "/tmp/backups"
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      CLUSTER_HOSTNAME: "node1"
      AUTOSCHEMA_ENABLED: 'false'
      DISABLE_TELEMETRY: 'true'
      GRPC_PORT: 8021
  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate-proxy:8020
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-v1.2.0
    ports:
      - 9999:9999
  proxy-http:
    image: envoyproxy/envoy:v1.29-latest
    command: envoy --config-path /etc/envoy/http.yaml
    ports:
      - 10000:10000
    volumes:
      - ./proxy:/etc/envoy
  proxy-grpc:
    image: envoyproxy/envoy:v1.29-latest
    command: envoy --config-path /etc/envoy/grpc.yaml
    ports:
      - 10001:10000
    volumes:
      - ./proxy:/etc/envoy
...
